# Generated by Django 3.0.6 on 2020-09-19 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('disindb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 10, 5, 52, 426708, tzinfo=utc)),
        ),
    ]
